### PR TITLE
Added support for GraphicsMagick naming convention of sizes

### PR DESCRIPTION
**Pull request by plopp**
Have not added any tests for this though.

However, great code, thanks for your work!

### CODE REVIEW

**Comment by patrickkettner** [comment]
Awesome!

Would you mind adding tests?

**Comment by plopp** [comment]
Sure, will fix this ASAP.

Found all existing formats from the GraphicsMagick source:
```
    case 0: break;
    case 1: (void) strcat(format,"Ki"); break; /* kilo, 10^3 */
    case 2: (void) strcat(format,"Mi"); break; /* mega, 10^6 */
    case 3: (void) strcat(format,"Gi"); break; /* giga, 10^9 */
    case 4: (void) strcat(format,"Ti"); break; /* tera, 10^12 */
    case 5: (void) strcat(format,"Pi"); break; /* peta, 10^15 */
    case 6: (void) strcat(format,"Ei"); break; /* exa,  10^18 */
```

**Comment by plopp** [comment]
Alright, added som tests. See if you find them appropriate. I also added support for decimal notation using comma and tests for that.

**Comment by patrickkettner** [comment]
thanks so much!

**Pull request merged**
